### ISSUE TITLE
dodat malo margine na dno ovih inputa :skull: 

### ISSUE THREAD

**Issue by bdeak4** [dump-hr/ddays-app#229]
![image](https://github.com/dump-hr/ddays-app/assets/32748145/718f39f9-511a-4cd2-8e99-4ce1449c6fee)

**Comment by bdeak4** [comment]
tribaju bit 16px

**Comment by bdeak4** [comment]
![image](https://github.com/dump-hr/ddays-app/assets/32748145/61679190-5ab5-4588-a1f7-ec4474d18139)
ista stvar vridi za oglase za posao na profilu

**Comment by drmodun** [comment]
> ![image](https://private-user-images.githubusercontent.com/32748145/305754915-61679190-5ab5-4588-a1f7-ec4474d18139.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0NDg1MzIsIm5iZiI6MTcwODQ0ODIzMiwicGF0aCI6Ii8zMjc0ODE0NS8zMDU3NTQ5MTUtNjE2NzkxOTAtNWFiNS00NTg4LWExZjctZWM0NDc0ZDE4MTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDE2NTcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ5NTEzN2NlODFhN2U3NmJkYjEwOWY3YzU1MzNmYjZiMzAzNmQyMTY3ZjA2NzI3ZWUxOGE4MGMxOThlYzA5M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rn3vrKH3_Jnc2Wu8JGEb5eyV7CvBGU81Z3UX1DO2zV8) ista stvar vridi za oglase za posao na profilu

Jel mislis ovdje promjeniti da je veci gap il dodat neku marginu? Posto meni se cini da su oglasi vec odvojeni. zasad cu povecati gap al ako nie to reci
